apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: "mydriving-api"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: "5a1cf1f8-6d21-4634-8770-0f6462cc80d0"  # Set the clientID of the user-assigned managed identity to use
    keyvaultName: "kvoh17112022"       # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret
          objectVersion: ""
    tenantId: "a21e886c-3079-4ce4-8093-bfb65ce69cc8"