name: Continuous integration

on: [push]

env:
  ARC_NAME: registrykar3457
  GIT_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      IMAGE_CREATE_DATE: ${{ steps.envs.outputs.IMAGE_CREATE_DATE }}
      IMAGE_SOURCE_REVISION: ${{ steps.envs.outputs.IMAGE_SOURCE_REVISION }}
      IMAGE_VERSION: ${{ steps.envs.outputs.IMAGE_VERSION }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          # Fetches the entire project history, required becuase we after use "git describe" which looks into the tree
          fetch-depth: 0
      - id: envs
        name: Init dynamic env vars
        run: |
          echo "IMAGE_CREATE_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "IMAGE_SOURCE_REVISION=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "IMAGE_VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
  build:
    name: Build sources & Publish containers
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
      - name: Login to Azure Container Registry (ARC)
        run: |
          az acr login -n ${{ env.ARC_NAME }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push "poi-api"
        uses: docker/build-push-action@v3
        with:
          context: ./src/poi
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ARC_NAME }}.azurecr.io/poi-api:latest
            ${{ env.ARC_NAME }}.azurecr.io/poi-api:${{ needs.prepare.outputs.IMAGE_VERSION }}
            ${{ env.ARC_NAME }}.azurecr.io/poi-api:${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            ${{ env.ARC_NAME }}.azurecr.io/poi-api:${{ env.GIT_BRANCH_NAME }}
          build-args: |
            IMAGE_CREATE_DATE=${{ needs.prepare.outputs.IMAGE_CREATE_DATE }}
            IMAGE_SOURCE_REVISION=${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            IMAGE_VERSION=${{ needs.prepare.outputs.IMAGE_VERSION }}
          cache-from: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/poi-api:${{ env.GIT_BRANCH_NAME }}
          cache-to: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/poi-api:${{ env.GIT_BRANCH_NAME }}
      - name: Build and push "trips-api"
        uses: docker/build-push-action@v3
        with:
          context: ./src/trips
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ARC_NAME }}.azurecr.io/trips-api:latest
            ${{ env.ARC_NAME }}.azurecr.io/trips-api:${{ needs.prepare.outputs.IMAGE_VERSION }}
            ${{ env.ARC_NAME }}.azurecr.io/trips-api:${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            ${{ env.ARC_NAME }}.azurecr.io/trips-api:${{ env.GIT_BRANCH_NAME }}
          build-args: |
            IMAGE_CREATE_DATE=${{ needs.prepare.outputs.IMAGE_CREATE_DATE }}
            IMAGE_SOURCE_REVISION=${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            IMAGE_VERSION=${{ needs.prepare.outputs.IMAGE_VERSION }}
          cache-from: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/trips-api:${{ env.GIT_BRANCH_NAME }}
          cache-to: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/trips-api:${{ env.GIT_BRANCH_NAME }}
      - name: Build and push "trips-viewer"
        uses: docker/build-push-action@v3
        with:
          context: ./src/tripviewer
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ARC_NAME }}.azurecr.io/trips-viewer:latest
            ${{ env.ARC_NAME }}.azurecr.io/trips-viewer:${{ needs.prepare.outputs.IMAGE_VERSION }}
            ${{ env.ARC_NAME }}.azurecr.io/trips-viewer:${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            ${{ env.ARC_NAME }}.azurecr.io/trips-viewer:${{ env.GIT_BRANCH_NAME }}
          build-args: |
            IMAGE_CREATE_DATE=${{ needs.prepare.outputs.IMAGE_CREATE_DATE }}
            IMAGE_SOURCE_REVISION=${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            IMAGE_VERSION=${{ needs.prepare.outputs.IMAGE_VERSION }}
          cache-from: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/trips-viewer:${{ env.GIT_BRANCH_NAME }}
          cache-to: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/trips-viewer:${{ env.GIT_BRANCH_NAME }}
      - name: Build and push "users-api"
        uses: docker/build-push-action@v3
        with:
          context: ./src/user-java
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ARC_NAME }}.azurecr.io/users-api:latest
            ${{ env.ARC_NAME }}.azurecr.io/users-api:${{ needs.prepare.outputs.IMAGE_VERSION }}
            ${{ env.ARC_NAME }}.azurecr.io/users-api:${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            ${{ env.ARC_NAME }}.azurecr.io/users-api:${{ env.GIT_BRANCH_NAME }}
          build-args: |
            IMAGE_CREATE_DATE=${{ needs.prepare.outputs.IMAGE_CREATE_DATE }}
            IMAGE_SOURCE_REVISION=${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            IMAGE_VERSION=${{ needs.prepare.outputs.IMAGE_VERSION }}
          cache-from: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/users-api:${{ env.GIT_BRANCH_NAME }}
          cache-to: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/users-api:${{ env.GIT_BRANCH_NAME }}
      - name: Build and push "profiles-api"
        uses: docker/build-push-action@v3
        with:
          context: ./src/userprofile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.ARC_NAME }}.azurecr.io/profiles-api:latest
            ${{ env.ARC_NAME }}.azurecr.io/profiles-api:${{ needs.prepare.outputs.IMAGE_VERSION }}
            ${{ env.ARC_NAME }}.azurecr.io/profiles-api:${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            ${{ env.ARC_NAME }}.azurecr.io/profiles-api:${{ env.GIT_BRANCH_NAME }}
          build-args: |
            IMAGE_CREATE_DATE=${{ needs.prepare.outputs.IMAGE_CREATE_DATE }}
            IMAGE_SOURCE_REVISION=${{ needs.prepare.outputs.IMAGE_SOURCE_REVISION }}
            IMAGE_VERSION=${{ needs.prepare.outputs.IMAGE_VERSION }}
          cache-from: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/profiles-api:${{ env.GIT_BRANCH_NAME }}
          cache-to: type=registry, ref=${{ env.ARC_NAME }}.azurecr.io/profiles-api:${{ env.GIT_BRANCH_NAME }}
